#!/bin/bash
echo -e "\033[1;34m"
echo "=========================================================="
echo " ___       _       _   ____ _____ ___  "
echo "|_ _|_ __ | |_ ___| | | __ )___  / _ \ "
echo " | || '_ \| __/ _ \ | |  _ \  / / | | |"
echo " | || | | | ||  __/ | | |_) |/ /| |_| |"
echo "|___|_| |_|\__\___|_| |____//_/  \___/ "
echo "                                       "
echo "   Intel Arc Pro B70 AI Toolbox (vLLM Scaler 0.14.0)      "
echo "=========================================================="
echo -e "\033[0m"
echo "  - Optimized for: Intel Arc Pro B70 / Ubuntu 25.04"
echo "  - To start vLLM serving, run: start-vllm"
echo ""
