#!/bin/bash
echo -e "\033[1;34m"
echo "=========================================================="
echo "    __    __    __  ___   ____        __    __            "
echo "   / /   / /   /  |/  /  / __ \      / /_  / /_  ___      "
echo "  / /   / /   / /|_/ /  / / / /____ / __ \/ __ \/ _ \     "
echo " / /___/ /___/ /  / /  / /_/ /_____/ /_/ / /_/ /  __/     "
echo "/_____/_____/_/  /_/  /_____/     /_.___/\____/\___/      "
echo "                                                          "
echo "   Intel Arc Pro B70 AI Toolbox (vLLM Scaler 1.3)         "
echo "=========================================================="
echo -e "\033[0m"
echo "  - Optimized for: Intel Arc Pro B70 / Ubuntu 25.04"
echo "  - To start vLLM serving, run: start-vllm"
echo ""
